apiVersion: v1
kind: Service
metadata:
  name: jxwaf-admin-server
  namespace: jxwaf  # 指定名称空间
spec:
  selector:
    app: jxwaf-admin-server
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
  - port: 443
    targetPort: 443
    nodePort: 30443
  type: NodePort
