apiVersion: v1
kind: Secret
metadata:
  name: jxwaf-ssl-certs
  namespace: jxwaf  # 指定名称空间
type: Opaque
data:
  server.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tC...  # 替换为server.crt的Base64编码
  server.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tC...  # 替换为server.key的Base64编码
