apiVersion: v1
kind: Service
metadata:
  name: mysql-db
  namespace: jxwaf  # 指定名称空间
spec:
  selector:
    app: mysql-db
  ports:
  - port: 3306
    targetPort: 3306
  clusterIP: None  # Headless Service，提供稳定DNS
