apiVersion: v1
kind: Service
metadata:
  name: clickhouse
  namespace: jxwaf
spec:
  selector:
    app: clickhouse
  ports:
  - port: 9000
    targetPort: 9000
    name: port9000
  - port: 9004
    targetPort: 9004
    name: port9004
  clusterIP: None  # Headless service，用于稳定的网络标识
