#!/bin/bash

# 预先在 Secrets Manager 中存储 JXWAF_SERVER 和 WAF_AUTH，开启加密。
# 在用户数据脚本中调用 AWS CLI 拉取密钥：
JXWAF_SERVER=$(aws secretsmanager get-secret-value --secret-id jxwaf_server_url --query SecretString --output text)
WAF_AUTH=$(aws secretsmanager get-secret-value --secret-id jxwaf_auth_key --query SecretString --output text)
export JXWAF_SERVER
export WAF_AUTH

yum update -y
yum install -y docker git vim

service docker start

# 下面这步如果只是为了让ec2-user能直接操作docker，用户数据没法刷新登录态，启动阶段用root执行也可以操作docker。
usermod -a -G docker ec2-user

# 安装 docker compose 插件
curl -SL https://github.com/docker/compose/releases/latest/download/docker-compose-linux-$(uname -m) -o /usr/libexec/docker/cli-plugins/docker-compose
chmod +x /usr/libexec/docker/cli-plugins/docker-compose
docker compose version

# 克隆代码库并启动服务
cd /home/ec2-user
git clone https://github.com/0671/jxwaf.git

cd jxwaf/jxwaf_node

# 以root身份启动docker compose
docker compose up -d
